### PR TITLE
Do not spawn visibile consoles, hide certutil window

### PR DESCRIPTION
**Pull request by StefanoBalzarottiNozomi**

### CODE REVIEW

**Comment by LordNoteworthy** [comment]
Looks good ! thank you.

**Comment by StefanoBalzarottiNozomi** [comment]
> Looks good ! thank you.
> 
> Do we probably need to: `go build -ldflags="-H windowsgui"` ?

That's not related.

If you compile with `go build -ldflags="-H windowsgui"` Go application will start in GUI mode without a console, no stdin nor stdout, but it will still spawn **certutil** windows if you don't specify `&syscall.SysProcAttr{HideWindow: true}`

The problem is particularly evident on slow machines, because the **certutil** opens and close very fast, maybe if you have a fast machine you will not notice, but in my case it's very annoying.

**Comment by LordNoteworthy** [comment]
I see, thanks a lot for the clarification.

**Comment by LordNoteworthy** [comment]
Forgot to add a build constraint, I will make a PR to fix that.

**Comment by LordNoteworthy** [comment]
@StefanoBalzarottiNozomi can you have a quick look into this please https://github.com/saferwall/pe/pull/94 ?

**Pull request merged**
